'use strict';
console.log('hello, world');
const heading = document.querySelector('h1');
const explanation = document.querySelector('#explanation');
const hint = document.querySelector('.hint');
const paragraphs = document.querySelectorAll('p');
const links = document.querySelectorAll('.example-link');
console.log('hheading', heading);
console.log('explanation', explanation);
console.log('hint', hint);
console.log('paragraphs', paragraphs);
console.log('links', links);
