'use strict';
const totalPets = 2;
const fullName = 'Ryan Griego';
const isCool = true;
const unknown = null;
const never = undefined;
console.log('Full Name ' + fullName);
console.log('Total Pets ' + totalPets);
console.log('Is cool ' + isCool);
console.log('Full Name typeof ' + typeof fullName);
console.log('Total Pets typeof ' + typeof totalPets);
console.log('Is cool typeof ' + typeof isCool);
console.log('unknown ' + unknown);
console.log('unknown typeof ' + typeof unknown);
console.log('never ' + never);
console.log('never typeof ' + typeof never);
