'use strict';
const width = 4;
const height = 6;
const area = width * height;
console.log('area', area);
console.log('typeof area', typeof area);
const bill = 22;
const payment = 32;
const change = payment - bill;
console.log('change', change);
console.log('typeof change', typeof change);
const quizzes = 10;
const midterm = 2;
const final = 1;
const grade = (quizzes + midterm + final) / 3;
console.log('log the grade', grade);
console.log('log the typeof grade', typeof grade);
const firstName = 'Ryan';
const lastName = 'Griego';
const fullName = firstName + ' ' + lastName;
console.log('log the fullName', fullName);
console.log('log thetypeof  fullName', typeof fullName);
const pH = 3;
const isAcidic = pH < 7;
console.log('log the isAcidic', isAcidic);
console.log('log the typeof  isAcidic', typeof isAcidic);
const headCount = 4;
const isSparta = headCount === 300;
console.log('log the isSparta', isSparta);
console.log('log the typeof  isSparta', typeof isSparta);
let motto = fullName;
motto = fullName + ' is the GOAT';
console.log('log motto', motto);
console.log('log typeof motto', typeof motto);
